version: '3.4'

services:
  api:
    image: gentcod/blog-share
    restart: unless-stopped 
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - blog-share-network
    environment:
      NODE_ENV: production
    env_file:
      - .config.prod.env
  proxy:
    restart: unless-stopped 
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on: 
      - api
    networks:
    - blog-share-network
networks: 
  blog-share-network:
    driver: bridge
