name: Deploy to Docker Hub using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .env file
      run: echo "${{ secrets.COMPOSE_ENV }}" > config.prod.env

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USR }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and Push with Docker Compose
      run: |
        docker compose -f prod-compose.yml build
        docker compose push
